/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FieldItemAdder.java
 *
 * Created on May 31, 2011, 9:25:42 PM
 */
package org.amityregion5.projectx.client.gui;

import org.amityregion5.projectx.client.communication.CommunicationHandler;
import org.amityregion5.projectx.common.communication.messages.RequestEntityAddMessage;
import org.amityregion5.projectx.common.entities.Entity;
import org.amityregion5.projectx.common.entities.items.field.Block;
import org.amityregion5.projectx.common.entities.items.field.Fence;
import org.amityregion5.projectx.common.entities.items.field.Wall;

/**
 * 
 * @author Daniel Centore
 * @deprecated Removing it soon
 */
public class FieldItemAdder extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    
    private CommunicationHandler ch;
    private int x;
    private int y;

    /** Creates new form FieldItemAdder */
    public FieldItemAdder(java.awt.Frame parent, boolean modal, CommunicationHandler ch, int x, int y, int loadX, int loadY)
    {
        super(parent, modal);
        
        this.ch = ch;
        this.x = x;
        this.y = y;
        
        initComponents();
        this.setLocation(loadX, loadY);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        itemGroup = new javax.swing.ButtonGroup();
        radioBlock = new javax.swing.JRadioButton();
        radioFence = new javax.swing.JRadioButton();
        radioWall = new javax.swing.JRadioButton();
        okayButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        itemGroup.add(radioBlock);
        radioBlock.setSelected(true);
        radioBlock.setText("Block");

        itemGroup.add(radioFence);
        radioFence.setText("Fence");

        itemGroup.add(radioWall);
        radioWall.setText("Wall");

        okayButton.setText("Okay");
        okayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okayButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        addLabel.setText("What would you like to add?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(okayButton).addGap(18, 18, 18).addComponent(cancelButton)).addComponent(addLabel).addComponent(radioBlock).addComponent(radioFence).addComponent(radioWall)).addContainerGap(82, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(addLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(radioBlock).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(radioFence).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(radioWall).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(okayButton).addComponent(cancelButton)).addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        this.setVisible(false);
    }

    private void okayButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        Entity e = null;
        if (radioBlock.isSelected())
        {
            e = new Block(x, y);
        } else if (radioFence.isSelected())
        {
            e = new Fence(x, y);
        } else if (radioWall.isSelected())
        {
            e = new Wall(x, y);
        }
        
//        ch.send(new RequestEntityAddMessage(e));
        
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.ButtonGroup itemGroup;
    private javax.swing.JButton okayButton;
    private javax.swing.JRadioButton radioBlock;
    private javax.swing.JRadioButton radioFence;
    private javax.swing.JRadioButton radioWall;
    // End of variables declaration//GEN-END:variables
}
